config/routes.rb
Funalyzer::Application.routes.draw do
  get "matlab/pca_lda", as: 'matlab_pca_lda'
  post 'matlab/pca_lda' => 'matlab#run_pca_lda'
  get "matlab/pca_qda", as: 'matlab_pca_qda'
  post 'matlab/pca_qda' => 'matlab#run_pca_qda'
  get "matlab/wilcoxon_rank_sum_test", as: 'matlab_wilcoxon_rank_sum_test'
  post 'matlab/wilcoxon_rank_sum_test' => 'matlab#run_wilcoxon_rank_sum_test'
  get "matlab/welch_ttest", as: 'matlab_welch_ttest'
  post 'matlab/welch_ttest' => 'matlab#run_welch_ttest'

  get "rscript/pca", as: 'rscript_pca'
  post 'rscript/pca' => 'rscript#run_pca'

  get "projects/:id/extract/show" => 'extraction#show', as: 'show_project_extract'
  post "projects/:id/extract/show" => 'extraction#search'
  post "projects/:id/extract" => 'extraction#extract', as: 'extract_project_extract'
  get "projects/:id/extract", to: redirect('projects/:id/extract/show')

  resources :projects do
    member do
      get   'labels' => 'labels#index'
      patch 'labels' => 'labels#update'
      get   'delete' => 'projects#delete'
      get   'delete_records' => 'projects#show_delete_records'
      post  'delete_records' => 'projects#delete_records'
    end

    resources :records, only: [:show, :new, :create, :edit, :update, :destroy] do
      collection do
        get 'new_next' => 'records#new_next'
      end
    end
  end
  root 'projects#index'

end

app/controllers/extraction_controller.rb
class ExtractionController < ApplicationController
  before_action :prepare_project
  before_action :prepare_search, only: [:search, :extract]

  def show
    @columns = Label.where(project_id: @project.id).where("white_list != ?", "")
  end

  def search
    render :show
  end

  def extract
    if params[:ids].try(:any?)
      files = {}

      # parse params
      case params[:data_format]
      when "csv"
        delimiter = ","
        extension = "csv"
      else
        delimiter = "\t"
        extension = "tsv"
      end
      lower_limit = params[:m_z_lower_limit].try(:to_f) || @project.m_z_start
      higher_limit = params[:m_z_higher_limit].try(:to_f) || @project.m_z_end

      # check excluding m/z value whether it match m/z of project
      excluding_m_z = params[:exclude_m_z] ? params[:exclude_m_z].split(/,|\t/).map(&:to_f) : []

      # prepare files
      extracted_spectra, selectors = @project.extract_spectra(
                                        params[:group_name],
                                        params[:ids],
                                        lower_limit,
                                        higher_limit,
                                        params[:exclude_null],
                                        excluding_m_z
                                      )
      extracted_spectra = extracted_spectra.map{|v| v.join(delimiter)}.join("\n")
      file_name = "#{params[:group_name]}(#{params[:ids].size})mz(#{@project.m_z_to_a[selectors.min]}-#{@project.m_z_to_a[selectors.max]}).#{extension}"
      files[file_name] = extracted_spectra
      files["mz.tsv"] = details_of_selectors(selectors, @project, lower_limit, higher_limit)

      files["details_of_spectra.tsv"] = details_of_spectra(@records, @table_header)

      files["condition_of_extraction.tsv"] = condition_of_searching

      # save files to desktop
      dir_name = "funalyzer_#{Time.now.strftime("%y%m%d")}"
      dir_name << "_#{params[:group_name]}" if params[:group_name] != ""
      save_result_to_desktop(dir_name, files)

      flash[:notice] = "Extraction was completed succesfully. Extracted files have been saved on your Desktop."
    end

    render :show
  end



  private
    def prepare_project
      @project = Project.find(params[:id])
    end

    def prepare_search
      @columns = Label.where(project_id: @project.id).where("white_list != ?", "")
      @table_header = @project.table_header
      @records = @project.get_table_class.where(search_params)
    end

    def search_params
      return nil unless params[:search]
      params.require(:search)
    end

    def details_of_selectors(selectors, project, lower_limit, higher_limit)
      index_l = project.m_z_lower(lower_limit)
      index_h = project.m_z_higher(higher_limit)
      ids_excluded = (index_l..index_h).to_a - selectors.to_a

      m_z = project.m_z_to_a

      return result = <<EOF
m/z information of Project #{project.name}
start\t#{project.m_z_start.to_s}
end\t#{project.m_z_end.to_s}
inverval\t#{project.m_z_interval}

exact m/z of Project #{project.name}\t#{m_z.join("\t")}
m/z included in extracted file\t#{m_z.values_at(*selectors).join("\t")}
m/z excluded in extracted file\t#{m_z.values_at(*ids_excluded).join("\t")}
EOF
    end

    def details_of_spectra(records, header)
      result = ""
      result << header.join("\t") << "\n"
      records.each do |record|
        tmp = []
        header.each do |column|
          tmp << record.send(column)
        end
        result << tmp.join("\t") << "\n"
      end
      result
    end

    def condition_of_searching
      return "nothing particular" unless params[:search]

      result = "label name\tconditions\n"
      params[:search].each_pair do |name, ary|
        tmp = [name] + ary
        result << tmp.join("\t") << "\n"
      end
    end

    def save_result_to_desktop(dir_name, files={})
      Dir.chdir(Dir.home + "/Desktop") do
        i = 0
        dir_name_tmp = dir_name
        while Dir.exists?(dir_name_tmp)
          i += 1
          dir_name_tmp = dir_name + "-#{i.to_s}"
        end

        Dir.mkdir(dir_name_tmp, 0775)

        Dir.chdir(dir_name_tmp) do
          files.each_pair do |file_name, content|
            File.open(file_name, "w") do |file|
              file.puts content
            end
          end
        end
      end
    end
end

app/helpers/extraction_helper.rb
module ExtractionHelper
end

app/views/extraction/show.html.erb
<h1>Extract Data</h1>

<% if notice %>
  <p class="uk-alert">
    <%= notice %>
  </p>
<% end %>

<h2>Searching</h2>
<div class="my-fields">
  <%= form_tag show_project_extract_path(@project) do %>
    <% if @columns.any? %>
      <table class="my-table">
        <thead>
          <% @columns.each do |column| %>
            <th>
              <%= column.name %>
            </th>
          <% end %>
        </thead>
        <tbody>
          <tr>
            <% @columns.each do |column| %>
              <td>
                <select name="search[<%= column.name %>][]" style="height:200px;" multiple>
                  <%= options_for_select column.white_list.split("\n").map{|v| [v,v]}, params[:search].try(:fetch, column.name,nil) %>
                </select>
              </td>
            <% end %>
          </tr>
        </tbody>
      </table>
    <% else %>
      No labels or only free text label is defined.
    <% end %>

    <p>
      * multiple selection is allowed.
    </p>

    <div class="fields">
      <%= submit_tag 'Search', class: 'uk-button uk-button-large uk-button-primary' %>
    </div>
  <% end %>
</div>


<div id="searched" class="my-fields">
  <% if @records %>

    <h2>Extraction</h2>

    <%= form_tag extract_project_extract_path(@project), class: 'uk-form uk-form-horizontal' do %>

      <% if params[:search] %>
        <% params[:search].each_pair do |name, ary| %>
          <% ary.each do |value| %>
            <%= hidden_field_tag "search[#{name}][]", value %>
          <% end %>
        <% end %>
      <% end %>

      <fieldset>
        <legend>Searched data</legend>

        <table class="my-table my-table-tablesorter">
          <thead>
            <tr>
              <th>
                use?
              </th>
              <% @table_header.each do |column| %>
                <th>
                  <%= column %>
                </th>
              <% end %>
            </tr>
          </thead>
          <tbody>
            <% @records.each do |record| %>
              <tr id="<%= record.id %>">
                <td>
                  <% if params[:ids] %>
                    <% flg = params[:ids].include?(record.id.to_s) ? true : false %>
                  <% else %>
                    <% flg = true %>
                  <% end %>
                  <%= check_box_tag 'ids[]', record.id, flg %>
                </td>

                <% @table_header.each do |column| %>
                  <% col = record.send(column) %>
                  <% case column %>
                  <% when :id %>
                    <td class="uk-text-center">
                      <%= link_to col, project_record_path(@project, record) %>
                    </td>
                  <% when :created_at, :updated_at %>
                    <td>
                      <%= col.strftime("%Y/%m/%d %H:%M") %>
                    </td>
                  <% when :spectrum_total_intensity %>
                    <td>
                      <%= sprintf("%.3e", col.to_f) %>
                    </td>
                  <% else %>
                    <td>
                      <%= col %>
                    </td>
                  <% end %>
                <% end %>
              </tr>
            <% end %>
          </tbody>
        </table>

        <% if @records.empty? %>
          No data was found.
        <% end %>
      </fieldset>

      <fieldset>
        <legend>Options</legend>

        <div class="uk-form-row">
          <label class="uk-form-label">
            Group Name
          </label>
          <div class="uk-form-controls">
            <%= text_field_tag 'group_name', params[:group_name] %>
          </div>
        </div>

        <div class="uk-form-row">
          <label class="uk-form-label">
            Lower limit of m/<span class="my-italic">z</span>
          </label>
          <div class="uk-form-controls">
            <%= text_field_tag 'm_z_lower_limit', @project.m_z_start %>
          </div>
        </div>

        <div class="uk-form-row">
          <label class="uk-form-label">
            Higher limit of m/<span class="my-italic">z</span>
          </label>
          <div class="uk-form-controls">
            <%= text_field_tag 'm_z_higher_limit', @project.m_z_end %>
          </div>
        </div>

        <div class="uk-form-row">
          <label class="uk-form-label">
            Data format
          </label>
          <div class="uk-form-controls">
            <select name="data_format">
              <option value="tsv" selected>tsv</option>
              <option value="csv">csv</option>
            </select>
          </div>
        </div>

        <div class="uk-form-row">
          <label class="uk-form-label">
            Exclude NULL
          </label>
          <div class="uk-form-controls">
            <%= check_box_tag 'exclude_null', true, true %>
          </div>
        </div>

        <div class="uk-form-row">
          <label class="uk-form-label">
            Exclude m/<span class="my-italic">z</span>
          </label>
          <div class="uk-form-controls">
            <%= text_field_tag 'exclude_m_z', params[:exclude_m_z], placeholder: 'split m/z with comma or tab', size: 80 %>
          </div>
        </div>

        <p class="fileds">
          <%= submit_tag 'Store data for statistical analysis', class: 'uk-button uk-button-large uk-button-primary' %>
        </p>
      </fieldset>
    <% end %>


  <% end %>
</div>