config/routes.rb
Funalyzer::Application.routes.draw do
  get "matlab/pca_lda", as: 'matlab_pca_lda'
  post 'matlab/pca_lda' => 'matlab#run_pca_lda'
  get "matlab/pca_qda", as: 'matlab_pca_qda'
  post 'matlab/pca_qda' => 'matlab#run_pca_qda'
  get "matlab/wilcoxon_rank_sum_test", as: 'matlab_wilcoxon_rank_sum_test'
  post 'matlab/wilcoxon_rank_sum_test' => 'matlab#run_wilcoxon_rank_sum_test'
  get "matlab/welch_ttest", as: 'matlab_welch_ttest'
  post 'matlab/welch_ttest' => 'matlab#run_welch_ttest'

  get "rscript/pca", as: 'rscript_pca'
  post 'rscript/pca' => 'rscript#run_pca'

  get "projects/:id/extract/show" => 'extraction#show', as: 'show_project_extract'
  post "projects/:id/extract/show" => 'extraction#search'
  post "projects/:id/extract" => 'extraction#extract', as: 'extract_project_extract'
  get "projects/:id/extract", to: redirect('projects/:id/extract/show')

  resources :projects do
    member do
      get   'labels' => 'labels#index'
      patch 'labels' => 'labels#update'
      get   'delete' => 'projects#delete'
      get   'delete_records' => 'projects#show_delete_records'
      post  'delete_records' => 'projects#delete_records'
    end

    resources :records, only: [:show, :new, :create, :edit, :update, :destroy] do
      collection do
        get 'new_next' => 'records#new_next'
      end
    end
  end
  root 'projects#index'

end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :set_project, :set_labels
  before_action :set_record, only: [:show, :edit, :update, :destroy]

  # GET /records/1
  # GET /records/1.json
  def show
    @table_header = @project.table_header
  end

  # GET /records/new
  def new
    @record = @project.get_table_class.new()
    @record.project_id = @project.id
  end

  def new_next
    attributes = @project.get_table_class.last.try(:attributes).try(:reject) do |key, value|
      not Label.white_list(@project.id).keys.map(&:to_s).include?(key.to_s)
    end
    @record = @project.get_table_class.new(attributes)
    @record.project_id = @project.id

    render :new
  end

  # GET /records/1/edit
  def edit
  end

  # POST /records
  # POST /records.json
  def create
    p params
    @record = @project.get_table_class.new(record_params)
    @record.project_id = @project.id

    respond_to do |format|
      if parse_spectrum_params && @record.save
        format.html { redirect_to new_next_project_records_path(@project), notice: 'Record was successfully created. Enter next.' }
        # format.json { render action: 'show', status: :created, location: @record }
      else
        format.html { render action: 'new' }
        # format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /records/1
  # PATCH/PUT /records/1.json
  def update
    
    respond_to do |format|
      if parse_spectrum_params && @record.update(record_params)
        format.html { redirect_to project_path(@project), notice: 'Record was successfully updated.' }
        # format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        # format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /records/1
  # DELETE /records/1.json
  def destroy
    @record.destroy
    respond_to do |format|
      format.html { redirect_to project_path(@project) }
      # format.json { head :no_content }
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_record
      # @record = Record.find(params[:id])
      @record = @project.get_table_class.find(params[:id])
    end

    def set_project
      @project = Project.find(params[:project_id])
    end

    def set_labels
      @labels = Label.where(project_id: @project.id)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def record_params
      if params[:record]
        params.require(:record).permit(*Label.white_list(@project.id).keys.map(&:to_sym))
      else
        nil
      end
    end

    def parse_spectrum_params
      if params[:spectrum]

        case params[:spectrum_format]
        when "normalized"
          source = params[:spectrum].read
        when "raw"
          source = SpectrumUtil::Converter.normalize_raw_data(params[:spectrum].read)
        else
          raise ArgumentError, "Invalid spectrum format"
        end

        @record.set_spectrum(source)
        @record.spectrum_sample_id = File.basename(params[:spectrum].original_filename, ".*")

        if params[:spectrum_re_allocation]
          if /\A-?([1-9]\d*|0)(\.\d+)?\z/ =~ params[:spectrum_first_m_z] && @project.m_z_to_a.include?(params[:spectrum_first_m_z].to_f)
            first_m_z = params[:spectrum_first_m_z].to_f
            @record.spectrum_re_allocate_m_z(first_m_z)
          else
            @record.errors.add :spectrum, "Invalid m/z to re-allocate was submitted. It can't be found in m/z of this project."
            return false
          end
        end  
      end
      
      true
    end
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/records/_form.html.erb
<% if notice %>
  <p class="">
    <%= notice %>
  </p>
<% end %>

<% if @record.errors.any? %>
  <div id="error_explanation" class="uk-alert uk-alert-danger">
    <h2><%= pluralize(@record.errors.count, "error") %> prohibited this record from being saved:</h2>

    <ul>
    <% @record.errors.each do |key, msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<fieldset>
  <legend>Label</legend>
  <% if @labels.any? %>
    <% @labels.each do |column| %>
      <div class="uk-form-row">
        <label class="uk-form-label">
          <%= column.name %>
        </label>

        <div class="uk-form-controls">
          <% if column.white_list.split("\n") == [] %>
            <%= text_field_tag "record[#{column.name}]", @record.send(column.name.to_sym), size: 60 %>
          <% else %>
            <select name="record[<%= column.name %>]">
              <% column.white_list.split("\n").each do |choice| %>
                <% if choice[0] == '#' %>
                  <optgroup label="<%= choice[1..-1] %>" ><optgroup>
                <% else %>
                  <%= options_for_select [["&nbsp;#{choice}".html_safe, choice]], @record.send(column.name) %>
                <% end %>
              <% end %>
            </select>
          <% end %>
        </div>
      </div>
    <% end %>
  <% else %>
    <p>
      No label is defined.<br>
      Please add labels on <%= link_to 'Label management', labels_project_path(@project) %> page.
    </p>
  <% end %>
</fieldset>

<fieldset>
  <legend>Spectrum</legend>

  <% unless @record.new_record? %>
    <div class="uk-form-row">
      <label class="uk-form-label">
        Sample ID of spectrum
      </label>
      <div class="uk-form-controls">
        <%= @record.spectrum_sample_id %>
      </div>
    </div>
  <% end %>

  <div class="uk-form-row">
    <label class="uk-form-label">
      Spectrum Data
    </label>
    <div class="uk-form-controls">
      <%= file_field_tag :spectrum %>
    </div>
  </div>

  <div class="uk-form-row">
    <label class="uk-form-label">
      Spectrum Format
    </label>
    <div class="uk-form-controls">
      <select name="spectrum_format">
        <option value="raw">raw</option>
        <option value="normalized">converted(normalized)</option>
      </select>
    </div>
  </div>

  <div class="uk-form-row">
    <label class="uk-form-label">
      Options to input spectrum
    </label>
    <div class="uk-form-controls" style="padding-top:5px;">
      <div class="fields">
        <label>
          <%= check_box_tag :spectrum_re_allocation, "1", true %>
          Re-allocate m/<span class="my-italic">z</span> information
        </label>
      </div>
      <div class="fields">
        <label>
          &nbsp;&nbsp;&nbsp;&nbsp;The first m/<span class="my-italic">z</span> for re-allocating
          <%= text_field_tag :spectrum_first_m_z, @record.project.m_z_start %>
        </label>
      </div>
    </div>
  </div>
</fieldset>

app/views/records/edit.html.erb
<h1>Editing data</h1>

<%= form_for @record, url: project_record_path(@project, @record), html: {class: 'uk-form uk-form-horizontal', enctype: 'multipart/form-data'} do |f| %>
  <%= render partial: 'form', locals: {f:f} %>
  
  <div class="actions">
    <%= f.submit 'Submit', class: 'uk-button uk-button-primary uk-button-large' %>
  </div>
<% end %>


<div class="uk-text-right">
  <%= link_to 'delete this data', project_record_path(@project, @record), class: 'uk-button uk-button-mini uk-button-danger', method: :delete,  data: { confirm: 'Are you sure?' } %>
</div>

<p>
  <%= link_to 'Back', project_record_path(@project, @record), class: 'uk-button uk-button-large' %>
</p>

app/views/records/index.html.erb
<h1>Listing records</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @records.each do |record| %>
      <tr>
        <td><%= link_to 'Show', record %></td>
        <td><%= link_to 'Edit', edit_record_path(record) %></td>
        <td><%= link_to 'Destroy', record, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Record', new_record_path %>

app/views/records/new.html.erb
<h1>Input Data</h1>

<%= form_for @record, url: project_records_path(@project.id), html:{class: 'uk-form uk-form-horizontal', enctype: 'multipart/form-data'} do |f| %>
  <%= render partial: 'form', locals: {f:f} %>
  
  <div class="actions">
    <%= f.submit 'Submit and input next', class: 'uk-button uk-button-primary uk-button-large' %>
  </div>
<% end %>

<p>
  <%= link_to 'Back', project_path(@project), class: 'uk-button uk-button-large' %>
</p>

app/views/records/show.html.erb
<% if notice %>
  <p id="uk-alert">
    <%= notice %>
  </p>
<% end %>

<h3>Label Information</h3>
<hr>
<div class="my-fields">
  <table class="my-table">
    <thead>
      <tr>
        <% @table_header.each do |column| %>
          <th>
            <%= column %>
          </th>
        <% end %>
      </tr>
    </thead>
    <tbody>
        <tr id="<%= @record.id %>">
          <% @table_header.each do |column| %>
            <% col = @record.send(column) %>
            <% case column %>
            <% when :created_at, :updated_at %>
              <td>
                <%= col.strftime("%Y/%m/%d %H:%M") %>
              </td>
            <% when :id %>
              <td class="uk-text-center">
                <%= col %>
              </td>
            <% when :spectrum_total_intensity %>
              <td>
                <%= sprintf("%.3e", col.to_f) %>
              </td>
            <% else %>
              <td>
                <%= col %>
              </td>
            <% end %>
          <% end %>
        </tr>
    </tbody>
  </table>
</div>



<h3>Spectrum Information</h3>
<hr>
<div class="my-fields">
  <p>
    This spectrum has null at <%= m_z_which_have_null @record %> (m/<span class="my-italic">z</span>).
  </p>

  <div id="chart_div" class="my-fields" style="width: 1100px; height: 500px;">
  </div>

  <div>
    * You need Internet connection to draw a chart.
  </div>
</div>




<%= link_to 'Edit', edit_project_record_path(@project, @record), class: 'uk-button uk-button-large' %>



<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript">
  google.load("visualization", "1", {packages:["corechart"]});
  google.setOnLoadCallback(drawChart);
  function drawChart() {
    var data = google.visualization.arrayToDataTable([
      ['m/z', 'intensity'],
      <%= spectrum_for_chart @record %>
    ]);

    var options = {
      title: 'Spectrum of <%= @record.spectrum_sample_id %>',
      hAxis: {title: 'm/z', minValue: <%= @project.m_z_start %>, maxValue: <%= @project.m_z_end %>,ticks: <%= ticks_for_chart @project %>},
      vAxis: {title: 'intensity', format: "0.0E0"}
    };

    var chart = new google.visualization.LineChart(document.getElementById('chart_div'));
    chart.draw(data, options);
  }
</script>